on:
  release:
    types:
    - created

name: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Checkout sources
      uses: actions/checkout@v3

    - run: docker build . -t analoglabs/rosetta-explorer
    - run: docker push analoglabs/rosetta-explorer
